### ISSUE TITLE
Generic java implements / extends support on raml Types (not only serializable & c)

### ISSUE THREAD

**Issue by dmiorandi** [OnPositive/aml#17]
I don't know if this is legacy from raml0.8+jsonschema2pojo or if there is a better way on raml 1.0
but should be usefull to have the possibility to specify custom implements and extends raml, not only serializable & c. Btw this instructions should be read only from java converter and not from other (i.e. js)

**Comment by petrochenko-pavel-a** [comment]
```raml 
#%RAML 1.0 Library
uses:
  r2j: raml2java.raml
types:
  QMap:
    (r2j.mapsToExisting): java.util.LinkedHashMap
    type: object
  W:
    (r2j.extendExisting): javax.swing.JFrame
    (r2j.implementsExisting): [javax.swing.WindowConstants]
    properties:
      map: QMap
