### ISSUE TITLE
Multipackage raml generation

### ISSUE THREAD

**Issue by dmiorandi** [OnPositive/aml#18]
Possibility to specify on raml files custom packages (not only one general), to have more flexibility
i.e.: 

* common.raml com.mycompany.raml.common
* business1.raml com.mycompany.raml.myproject.section1
* business2.raml com.mycompany.raml.myproject.section2

Should be reasonable to implement?

**Comment by petrochenko-pavel-a** [comment]
Except of not object annotation types it worked in 0.0.10, documentation and sample added to 0.11-SNAPSHOT.

Regards,
Pavel
